### ISSUE TITLE
Native module question ...

### ISSUE THREAD

**Issue by AhmedMustafa505** [WilliamWelsh/WilliamWelsh#1]
Hello Mr.Welsh, 
I opened this issue just to reach out to you asking about the native module that you saw uploading files in react native windows instead of fetch or axios.

it's urgent for me because I've been stuck on this situation for weeks now, and I'm not familiar with creating native modules from scratch or C++/C# languages

@WilliamWelsh so if you can please support me with any ideas or links that maybe useful, I would appreciate it. 

Thanks in advance

**Comment by WilliamWelsh** [comment]
Continued from [here](https://github.com/microsoft/react-native-windows/issues/12168#issuecomment-1777654756)

Sure, I ended up having to make a native module and method to upload the file. When I initialized the windows part of my app, I did it with C# (`react-native-windows-init --language cs`).

Then in the C# project in visual studio, I made a new cs file named `WhateverModule.cs`, and it looks something like this:


```cs
using System.Net.Http;

namespace whatever
{
    [ReactModule]
    public class Whatever
    {
        [ReactMethod("Upload")]
        public async void Upload(string filePath)
        {
            using (var httpClient = new HttpClient())
            {
                var formData = new MultipartFormDataContent();

                // Add selectedFile
                var selectedFileStream = await selectedFile.OpenStreamForReadAsync();
                var fileContent = new StreamContent(selectedFileStream);
                fileContent.Headers.Add("Content-Type", "application/octet-stream");
                formData.Add(fileContent, "file", selectedFile.Name);

                var response = await httpClient.PostAsync("whatever url", formData);
            }
        }
    }
}
```

Of course your form data headers and stuff are probably different, but this is what I needed (I was uploading a set of files to a Discord channel via Discord webhook).

Then in your React Native app (your JS/TS part), in a top-levle file called `WindowsNativeModules.ts` in my case:

```ts
import type { TurboModule } from "react-native/Libraries/TurboModule/RCTExport";
import { TurboModuleRegistry } from "react-native";

export interface Spec extends TurboModule {
  Upload: (filePath: string) => void;
}

export default TurboModuleRegistry.get<Spec>("Whatever") as Spec | null;
```

Then, wherever you're gonna use it:

```ts
if (Platform.OS == "windows") {
      WindowsNativeModules.Upload(
        yourFilePath
      );
```

The docs below helped me a lot (there's no dark mode unfortunately)
https://microsoft.github.io/react-native-windows/docs/native-modules

**Comment by AhmedMustafa505** [comment]
@WilliamWelsh Thank you man for fast reply and your support !

my question is I'm implementing the file pick in my react native code using react-native-document-picker, and I see that you're passing the filePath only to the C# module, but you never used the filePath and the selectedFile is not defined as I think you picked or selected the file in the C# module. not in your React Native code.

**Comment by WilliamWelsh** [comment]
> I see that you're passing the filePath only to the C# module, but you never used the filePath

You're right, my bad:
```cs
using Windows.Storage; // Add this line

        [ReactMethod("Upload")]
        public async void Upload(string filePath)
        {

            // This too
            var selectedFile = await StorageFile.GetFileFromPathAsync(filePath);

            using (var httpClient = new HttpClient())
            {
                var formData = new MultipartFormDataContent();

                var selectedFileStream = await selectedFile.OpenStreamForReadAsync();
                var fileContent = new StreamContent(selectedFileStream);
                fileContent.Headers.Add("Content-Type", "application/octet-stream");
                formData.Add(fileContent, "file", selectedFile.Name);

                var response = await httpClient.PostAsync("whatever url", formData);
            }
        }
```



> my question is I'm implementing the file pick in my react native code using react-native-document-picker

Yes, in my case I already knew the exact file I wanted to upload, so the user wasn't picking a file from their system, and was retrieving the path using `react-native-fs`. I've never used `react-native-document-picker`, but according to their README maybe you can try [passing the resulting uri](https://github.com/rnmods/react-native-document-picker#uri)?

**Comment by AhmedMustafa505** [comment]
@WilliamWelsh  Have you modified anything in ReactPackageProvider.cs  or App.xaml.cs ?

**Comment by WilliamWelsh** [comment]
`ReactPackageProvider.cs` shouldn't need to be changed, but make sure you have the following lines in `App()` in `App.xaml.cs`

```cs
Microsoft.ReactNative.Managed.AutolinkedNativeModules.RegisterAutolinkedNativeModulePackages(
                PackageProviders
            );
PackageProviders.Add(new Microsoft.ReactNative.Managed.ReactPackageProvider());
PackageProviders.Add(new ReactPackageProvider());
```

**Comment by AhmedMustafa505** [comment]
I tried the following and still can't see any result, either the file is uploaded or it's failed to upload,

The react native based code:

```
import DocumentPicker  from 'react-native-document-picker';
import WindowsNativeModules from './WindowsNativeModules';


export default function App() {
  const pickDocument = async () => {
    console.log("pickDocument called");
    try {
      const pickerResult = await DocumentPicker.pick({
      presentationStyle: 'fullScreen',
      copyTo: 'documentDirectory',
      type: [DocumentPicker.types.allFiles],
    });
  
    console.log("Picker result URI:", pickerResult[0].uri);


  
    if (Platform.OS == "windows") {
    // @ts-ignore
      WindowsNativeModules.Upload(
        pickerResult[0].uri
      );
    }
    } catch (error) {
      console.error('Document picker error:', error);
    }
  };
```

```
import type { TurboModule } from "react-native/Libraries/TurboModule/RCTExport";
import { TurboModuleRegistry } from "react-native";

export interface Spec extends TurboModule {
  Upload: (filePath: string) => void;
}

export default TurboModuleRegistry.get<Spec>("Whatever") as Spec | null;
```

The module as you described:

```
using Microsoft.ReactNative.Managed;
using System;
using System.IO;
using System.Net.Http;
using Windows.Storage;

namespace whatever
{
    [ReactModule]
    public class Whatever
    {
        [ReactMethod("Upload")]
        public async void Upload(string filePath)
        {
            var selectedFile = await StorageFile.GetFileFromPathAsync(filePath);
            using (var httpClient = new HttpClient())
            {
                var formData = new MultipartFormDataContent();

                // Add selectedFile
                var selectedFileStream = await selectedFile.OpenStreamForReadAsync();
                var fileContent = new StreamContent(selectedFileStream);
                fileContent.Headers.Add("Content-Type", "application/octet-stream");
                formData.Add(fileContent, "file", selectedFile.Name);

                var response = await httpClient.PostAsync("http://192.168.1.193:3000/upload", formData);
            }
        }
    }
}
```
App.xaml.cs:

```
 sealed partial class App : ReactApplication
    {
        public App()
        {
          Microsoft.ReactNative.Managed.AutolinkedNativeModules.RegisterAutolinkedNativeModulePackages(
                            PackageProviders
                        );
            PackageProviders.Add(new Microsoft.ReactNative.Managed.ReactPackageProvider());
            PackageProviders.Add(new ReactPackageProvider());

            InitializeComponent();
        }
        
```

**Comment by WilliamWelsh** [comment]
Are you saying it's failing to run the upload code or are you saying you can't tell, from the React Native app, whether or not the file uploaded but you can see on your local server that it uploaded?

**Comment by AhmedMustafa505** [comment]
No, I meant that the file is not successfully uploaded to the back-end server.
I don't know if it can't run the upload code or not to be honest, because I don't get any logs regarding the module C# in Visual Studio.

**Comment by WilliamWelsh** [comment]
To get whether or not it was uploaded, you could do something like this:

In your `WindowsNativeModules.ts`
```ts
export interface Spec extends TurboModule {
  Upload: (filePath: string) => Promise<boolean>;
}
```

Then in CS
```cs
        [ReactMethod("Upload")]
        public async Task<bool> Upload(string filePath)
        {
            var selectedFile = await StorageFile.GetFileFromPathAsync(filePath);
            using (var httpClient = new HttpClient())
            {
                var formData = new MultipartFormDataContent();

                // Add selectedFile
                var selectedFileStream = await selectedFile.OpenStreamForReadAsync();
                var fileContent = new StreamContent(selectedFileStream);
                fileContent.Headers.Add("Content-Type", "application/octet-stream");
                formData.Add(fileContent, "file", selectedFile.Name);

                var response = await httpClient.PostAsync("http://192.168.1.193:3000/upload", formData);

                return response.IsSuccessStatusCode;
            }
        }
```

Then in your app
```ts
const didUpload = await WindowsNativeModules.Upload(
        filePath
      );
console.log({ didUpload });
```

I would double check your uri that is something like `C:\whatever` and paste it in your File Explorer url bar to make sure it's a correct uri.

I would also have your server log requests if you don't already.

And, in your C# project `Package.appxmanifest`, you might have to go to the Capabilities tab and make sure "Internet (Client & Server)" and "Internet (Client)" are both checked. I don't know if this is required, but it's enabled on mine.

I know it's pretty ridiculous to do all this just to upload a file from react native on windows 😂

**Comment by AhmedMustafa505** [comment]
I can guarantee to you that the file is not uploaded because I'm the one who created the back-end dummy server just to test the upload, the problem is I never dealt with C#. 

I got a new fresh error  :

error: Error: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
    at Object.promiseMethodWrapper [as Upload] 
    
    
I know I've been bothering you in your own repo, if you want to share with me any contact so I can reach out to you somewhere better than here let me know =)
  |

**Comment by WilliamWelsh** [comment]
In your `Package.appxmanifest` again, in Capabilities tab, try checking "Pictures Library" and then pick a file from your pictures library, if that fixes it then you might need [`broadFileSystemAccess`](https://www.jasongaylord.com/blog/2021/11/17/uwp-file-access-denied).

**Comment by AhmedMustafa505** [comment]
THANK YOU MAN !! 
it worked as expected I had to allow the broadFileSystemAccess and that enabled selecting files from any location and the file was uploaded successfully

**Comment by WilliamWelsh** [comment]
Glad I could help :)
